import { Book } from '@/app/types';

export const books: Book[] = [
  {
    id: 1,
    title: 'The Gems',
    author: 'M.C. Jeter',
    ageRange: ['New Adult'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Fantasy', 'Contemporary', 'Friends to Lovers', 'Found Family', 'Sensitive Content', 'Strong Female Lead'],
    cover: '/covers/thegems.png',
    description: 'When seventeen-year-old Ruby Jenkins discovers that her blood carries powerful magic, she must band together with new allies to stop her uncle from terrorizing the world.',
    link: 'https://a.co/d/hofcGNV',
  },
  {
    id: 2,
    title: 'Itchikan',
    author: 'Bin Userkaf',
    ageRange: ['Young Adult'],
    subGenres: ['Platonic Love', 'Self Love', 'Romantic Love'],
    tropes: ['Comedy', 'Coming of Age', 'Contemporary', 'Dystopian', 'Fantasy', 'Found Family', 'Friends to Lovers', 'Sci-Fi', 'Strong Female Lead'],
    cover: '/covers/itchikan.jpg',
    description: "Seventeen year old Aurora's sheltered life is changed forever when the merciless Queen of her hometown, Navajo City-State, announces a nefarious experiment that threatens the few things she holds dear.  Tired of sitting on the sidelines and eager for adventure, Aurora and her friends set out to stop it, sending them on a journey of chaotic proportions when things don't go as planned and they are forced to flee to Itchikan City-State.   Friendships are tested and foes are formed, but war is no place for the kind of adventure Aurora had in mind and if they are going to defeat the Queen, she will first have to defeat the darkness within herself.",
    link: 'https://a.co/d/cwu3sDM',
  },
  {
    id: 3,
    title: 'Lipstick & Camera Clicks',
    author: 'D. J. Murphy',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love', 'Familial Love'],
    tropes: ['Contemporary', 'Forced Proximity', 'Friends to Lovers', 'Interracial', 'Spicy (Low)', 'Strong Female Lead'],
    cover: '/covers/lipstickAndCam.jpg',
    description: "Indigo Johnson joins the cast of a reality dating show after a recent heartbreak leaves her craving change. She never expected to develop real feelings for the bachelor—or that her childhood best friend, now the show's producer, would reignite emotions she thought were long buried. Now, she’s caught in the spotlight, struggling to resist the growing spark with the leading man while pretending she’s over the one working behind the scenes.",
    link: 'https://a.co/d/1oEl7XA',
  },
  {
    id: 4,
    title: 'Bali Blue: A Wanderlust Romance Novel',
    author: 'Cher Terais',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love', 'Self Love'],
    tropes: ['Contemporary', 'Enemies to Lovers', 'Forced Proximity', 'Spicy (High)', 'Strong Female Lead', 'Work Place'],
    cover: '/covers/baliBlue.jpg',
    description: "After Rhiyan's marriage crashed and burned, she packed up and flew to Bali. Instead of healing, she’s met with a headache—Kendrick Kekoa. The tropical heat has nothing on the sparks between these two in Bali!",
    link: 'https://a.co/d/63DyzYE',
  },// Add more book objects...
  {
    id: 5,
    title: 'Recovery (A Marriage in Crisis)',
    author: 'Tay Latrese',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Forced Proximity', 'Spicy (Low)', 'Urban'],
    cover: '/covers/recovery.jpeg',
    description: 'Maurice and Neyehli Logan have been together for over a decade and have hit a roadblock in their marriage; tragedy. The two agree to book a weekend trip out in the middle of nowhere to try and salvage their relationship.',
    link: 'https://a.co/d/2bi9CnS',
  },
  {
    id: 6,
    title: 'Spend My Life With You',
    author: 'Monique Fisher',
    ageRange: ['Mature'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Comedy', 'Contemporary', 'Friends to Lovers', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/spendMyLifeWithYou.jpg',
    description: 'Thaddeus Richardson and Andrea Johnson are in love. Having wasted years staying quiet, they confess their feelings and immediately get married. The book follows their first year of marriage.',
    link: 'https://www.amazon.com/dp/B0DJWQBLLW',
  },
  {
    id: 7,
    title: "Breaking Point: Chandler's Choice",
    author: 'Carlotta Ardell',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary'],
    cover: '/covers/breakingPoint.jpg',
    description: "Chandler Gray never imagined during her journey to earn a nursing degree, she would encounter a distraction, in the form of firefighter, Moses Lawson. With the chaos of supporting her mother after her father's passing and completing her internship and practicum, Chandler had no time for a relationship. However, Moses' persistence, charisma, and rugged good looks made her think again. Perhaps a summer fling with no strings attached was just what the doctor ordered.  Unfortunately, their situationship became much more than she bargained for. Now Chandler wants Moses to switch things up to be in a committed and monogamous relationship. His response causes Chandler to react in ways she may come to regret.  Years later, when their paths cross in very different circumstances, Chandler will have another decision to make.  Can she look beyond her own hurt to give of herself and heal another past their breaking point?",
    link: 'https://a.co/d/d5Aqgcj',
  },
  {
    id: 8,
    title: 'Project Protection',
    author: 'Aiyana McCoy',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Fake Relationship', 'Forced Proximity', 'Interracial', 'Strong Female Lead', 'Sunshine x Grumpy'],
    cover: '/covers/projectProtection.jpg',
    description: 'Amelie a gun for hire becomes a bodyguard for the son of a CEO who is in danger from a mysterious attacker. He also asks her to be his fake girlfriend to keep his mother from trying to marry him off. ',
    link: 'https://www.amazon.com/dp/B0CL2D3FJC',
  },
  {
    id: 9,
    title: "She's A Grinder",
    author: 'Tember Sapphire',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Contemporary', 'Fake Relationship', 'Forbidden Love', 'Forced Proximity', 'Found Family', 'Strong Female Lead', 'Sunshine x Grumpy', 'Work Place'],
    cover: '/covers/shesAGrinder.jpg',
    description: "She's A Grinder is a fake dating hockey romance featuring Catherine a sports executive and her best friend’s brother and hockey grinder Tijjani.",
    link: 'https://a.co/d/0fNoXrU',
  },
  {
    id: 10,
    title: "Drunk in Love",
    author: 'Aaliyah Deana',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Friends to Lovers', 'Mystery', 'Spicy (Low)', 'Work Place'],
    cover: '/covers/drunkInLove.jpg',
    description: "Friends to lovers romantic suspense set in NYC. Maxwell and Kamaya must work together to track down a cyber criminal as their friendship and feelings toward each other develop in the mystery romance. ",
    link: 'https://www.amazon.com/gp/aw/d/B0D64Y7BTT',
  },
  {
    id: 11,
    title: "Sunflower",
    author: 'Aricka Alexander',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Friends to Lovers', 'Sapphic', 'Spicy (Low)', 'Strong Female Lead'],
    cover: '/covers/sunflower.png',
    description: "Autumn Noble is a 27-year-old mother who focuses all her time on working and being there for her daughter, Sydney. She has no time for relationships, going out, or partying. After the rocky relationship with her ex, she believes that maybe relationships just aren't for her. That is until she meets Winter. She's a fun-loving, spontaneous person who is attracted to Autumn from the first time they meet. With her personality and gentleness, she reintroduces the idea of love to Autumn.",
    link: 'https://a.co/d/dXw2MX7',
  },
  {
    id: 12,
    title: "Lust Drunk Nights",
    author: 'Kitty N Pawell',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Bisexual', 'Erotica', 'Insta-love', 'Sapphic', 'Spicy (High)', 'Strong Female Lead', 'Urban'],
    cover: '/covers/lustDrunkNights.jpg',
    description: "Lust Drunk Nights is a spicy read that will grip you tightly and leave you thirsty for more. Rose Thorne is the ultimate badass, who knows exactly what she wants and isn't afraid to go after it and claim it.",
    link: 'https://a.co/d/hegob75',
  },
  {
    id: 13,
    title: "The Warmest Melody",
    author: 'N. Sonia Nkera',
    ageRange: ['Young Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Enemies to Lovers', 'Incapable of Love', 'Sensitive Content', 'No Spice', 'Sunshine x Grumpy', 'Work Place'],
    cover: '/covers/warmestMelody.jpg',
    description: "Leah is excited to start her hospital residency under the young genius professor, Dante Guma. As the hospital's youngest professor and head of pediatrics, Dante is known for his brilliance and reserve. Even more than that, everyone knows that he prefers to work alone; Leah is the fresh thorn in his side.",
    link: 'https://www.amazon.com/dp/B0CKTMH8YW',
  },
  {
    id: 14,
    title: "Where the River Meets the Soul",
    author: 'S. Nicole',
    ageRange: ['Young Adult'],
    subGenres: ['Family Love', 'Platonic Love', 'Romantic Love'],
    tropes: ['Asexual', 'Bisexual', 'Fantasy', 'Fated Love', 'Forbidden Love', 'Friends to Lovers', 'Queer'],
    cover: '/covers/riverMeetsSoul.png',
    description: " It follows Heriath, an herbalist who goes on a mission to restore a magical flower to save her dying sister. She must reunite reincarnated soulmates to complete her task which proves easy at first, until she finds herself falling for one of the bonded pair.",
    link: 'https://www.amazon.com/dp/B0CGY3NQW6',
  },
  {
    id: 15,
    title: "Stroke Of Luck - Men If Nirvana Book One",
    author: 'Phoenix Collins',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Erotica', 'Forced Proximity', 'Incapable of Love', 'Sensitive Content', 'Spicy (High)', 'Strong Female Lead', 'Work Place'],
    cover: '/covers/strokeOfLuck.jpg',
    description: "When Carter Harrington, a billionaire who avoids emotional attachments, offers to help Lucky, a dancer rebuilding her life after heartbreak, sparks fly. What begins as a friends with benefits arrangement soon grows into something deeper, forcing them to face their fears and vulnerabilities. Together, they must decide if they can trust love enough to create a future neither thought possible.",
    link: 'https://a.co/d/2Oc6Jjo',
  },
  {
    id: 16,
    title: "How Far Is The Nearest Subway?",
    author: 'A M. R. S. K',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love', 'Familial Love', 'Platonic love'],
    tropes: ['Age Gap', 'Coming of Age', 'Contemporary', 'Found Family', 'Friends to Lovers', 'Interracial', 'Strong Female Lead', 'Unplanned Pregnancy', 'Work Place'],
    cover: '/covers/subway.jpeg',
    description: "A fish out of water story, “How Far Is The Nearest Subway?” centers around five friends who are M.R.S. Ks (moms raising southern kids). Through their life experiences as “framily”, these characters navigate living in their adopted hometown, Atlanta, Georgia, with friendship and laughter.",
    link: 'https://a.co/d/bLCE2KJ',
  },
  {
    id: 17,
    title: "Brandy",
    author: 'Kayla Love',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Fake Relationship', 'Small Town', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/brandy.jpg',
    description: "Brandy is looking forward to escaping to Bliss Bay for the summer. Imagine her surprise, when her ex unexpectedly shows up - with his new girlfriend! To pretend she's moved on, Brandy makes up a fake boyfriend. A serendipitous meeting leads to her finding a co conspirator for the ruse. While getting to know him, Brandy catches real feelings. But when complications arise, Brandy must decide: keep up the charade or risk it all for something genuine.",
    link: 'https://a.co/d/1QBosMc',
  },
  {
    id: 18,
    title: "Shoot For The Stars",
    author: 'Ciana Smoak',
    ageRange: ['Young Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Found Family', 'Friends to Lovers', 'Spice Not Included'],
    cover: '/covers/shootForStars.jpeg',
    description: "Journey Young starts fresh at a new School to win a track championship. She meets her childhood friend Roman and tries to focus on herself and not her growing feelings for Roman.",
    link: 'https://a.co/d/iOWpTre',
  },
]