import { Book } from '@/app/types';

export const books: Book[] = [
  {
    id: 1,
    title: 'The Gems',
    author: 'M.C. Jeter',
    ageRange: ['New Adult'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Fantasy', 'Contemporary', 'Friends to Lovers', 'Found Family', 'Sensitive Content', 'Strong Female Lead'],
    cover: '/covers/thegems.png',
    description: 'When seventeen-year-old Ruby Jenkins discovers that her blood carries powerful magic, she must band together with new allies to stop her uncle from terrorizing the world.',
    link: 'https://a.co/d/hofcGNV',
  },
  {
    id: 2,
    title: 'Itchikan',
    author: 'Bin Userkaf',
    ageRange: ['Young Adult'],
    subGenres: ['Platonic Love', 'Self Love', 'Romantic Love'],
    tropes: ['Comedy', 'Coming of Age', 'Contemporary', 'Dystopian', 'Fantasy', 'Found Family', 'Friends to Lovers', 'Sci-Fi', 'Strong Female Lead'],
    cover: '/covers/itchikan.jpg',
    description: "Seventeen year old Aurora's sheltered life is changed forever when the merciless Queen of her hometown, Navajo City-State, announces a nefarious experiment that threatens the few things she holds dear.  Tired of sitting on the sidelines and eager for adventure, Aurora and her friends set out to stop it, sending them on a journey of chaotic proportions when things don't go as planned and they are forced to flee to Itchikan City-State.   Friendships are tested and foes are formed, but war is no place for the kind of adventure Aurora had in mind and if they are going to defeat the Queen, she will first have to defeat the darkness within herself.",
    link: 'https://a.co/d/cwu3sDM',
  },
  {
    id: 3,
    title: 'Lipstick & Camera Clicks',
    author: 'D. J. Murphy',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love', 'Familial Love'],
    tropes: ['Contemporary', 'Forced Proximity', 'Friends to Lovers', 'Interracial', 'Spicy (Low)', 'Strong Female Lead'],
    cover: '/covers/lipstickAndCam.jpg',
    description: "Indigo Johnson joins the cast of a reality dating show after a recent heartbreak leaves her craving change. She never expected to develop real feelings for the bachelor—or that her childhood best friend, now the show's producer, would reignite emotions she thought were long buried. Now, she’s caught in the spotlight, struggling to resist the growing spark with the leading man while pretending she’s over the one working behind the scenes.",
    link: 'https://a.co/d/1oEl7XA',
  },
  {
    id: 4,
    title: 'Bali Blue: A Wanderlust Romance Novel',
    author: 'Cher Terais',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love', 'Self Love'],
    tropes: ['Contemporary', 'Enemies to Lovers', 'Forced Proximity', 'Spicy (High)', 'Strong Female Lead', 'Work Place'],
    cover: '/covers/baliBlue.jpg',
    description: "After Rhiyan's marriage crashed and burned, she packed up and flew to Bali. Instead of healing, she’s met with a headache—Kendrick Kekoa. The tropical heat has nothing on the sparks between these two in Bali!",
    link: 'https://a.co/d/63DyzYE',
  },// Add more book objects...
  {
    id: 5,
    title: 'Recovery (A Marriage in Crisis)',
    author: 'Tay Latrese',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Forced Proximity', 'Spicy (Low)', 'Urban'],
    cover: '/covers/recovery.jpeg',
    description: 'Maurice and Neyehli Logan have been together for over a decade and have hit a roadblock in their marriage; tragedy. The two agree to book a weekend trip out in the middle of nowhere to try and salvage their relationship.',
    link: 'https://a.co/d/2bi9CnS',
  },
  {
    id: 6,
    title: 'Spend My Life With You',
    author: 'Monique Fisher',
    ageRange: ['Mature'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Comedy', 'Contemporary', 'Friends to Lovers', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/spendMyLifeWithYou.jpg',
    description: 'Thaddeus Richardson and Andrea Johnson are in love. Having wasted years staying quiet, they confess their feelings and immediately get married. The book follows their first year of marriage.',
    link: 'https://www.amazon.com/dp/B0DJWQBLLW',
  },
  {
    id: 7,
    title: "Breaking Point: Chandler's Choice",
    author: 'Carlotta Ardell',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary'],
    cover: '/covers/breakingPoint.jpg',
    description: "Chandler Gray never imagined during her journey to earn a nursing degree, she would encounter a distraction, in the form of firefighter, Moses Lawson. With the chaos of supporting her mother after her father's passing and completing her internship and practicum, Chandler had no time for a relationship. However, Moses' persistence, charisma, and rugged good looks made her think again. Perhaps a summer fling with no strings attached was just what the doctor ordered.  Unfortunately, their situationship became much more than she bargained for. Now Chandler wants Moses to switch things up to be in a committed and monogamous relationship. His response causes Chandler to react in ways she may come to regret.  Years later, when their paths cross in very different circumstances, Chandler will have another decision to make.  Can she look beyond her own hurt to give of herself and heal another past their breaking point?",
    link: 'https://a.co/d/d5Aqgcj',
  },
  {
    id: 8,
    title: 'Project Protection',
    author: 'Aiyana McCoy',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Fake Relationship', 'Forced Proximity', 'Interracial', 'Strong Female Lead', 'Sunshine x Grumpy'],
    cover: '/covers/projectProtection.png',
    description: 'Amelie a gun for hire becomes a bodyguard for the son of a CEO who is in danger from a mysterious attacker. He also asks her to be his fake girlfriend to keep his mother from trying to marry him off. ',
    link: 'https://www.amazon.com/dp/B0CL2D3FJC',
  },
  {
    id: 9,
    title: "She's A Grinder",
    author: 'Tember Sapphire',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Contemporary', 'Fake Relationship', 'Forbidden Love', 'Forced Proximity', 'Found Family', 'Strong Female Lead', 'Sunshine x Grumpy', 'Work Place'],
    cover: '/covers/shesAGrinder.JPG',
    description: "She's A Grinder is a fake dating hockey romance featuring Catherine a sports executive and her best friend’s brother and hockey grinder Tijjani.",
    link: 'https://a.co/d/0fNoXrU',
  },
  {
    id: 10,
    title: "Drunk in Love",
    author: 'Aaliyah Deana',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Friends to Lovers', 'Mystery', 'Spicy (Low)', 'Work Place'],
    cover: '/covers/drunkInLove.jpg',
    description: "Friends to lovers romantic suspense set in NYC. Maxwell and Kamaya must work together to track down a cyber criminal as their friendship and feelings toward each other develop in the mystery romance. ",
    link: 'https://www.amazon.com/gp/aw/d/B0D64Y7BTT',
  },
  {
    id: 11,
    title: "Sunflower",
    author: 'Aricka Alexander',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Friends to Lovers', 'Sapphic', 'Spicy (Low)', 'Strong Female Lead'],
    cover: '/covers/sunflower.png',
    description: "Autumn Noble is a 27-year-old mother who focuses all her time on working and being there for her daughter, Sydney. She has no time for relationships, going out, or partying. After the rocky relationship with her ex, she believes that maybe relationships just aren't for her. That is until she meets Winter. She's a fun-loving, spontaneous person who is attracted to Autumn from the first time they meet. With her personality and gentleness, she reintroduces the idea of love to Autumn.",
    link: 'https://a.co/d/dXw2MX7',
  },
  {
    id: 12,
    title: "Lust Drunk Nights",
    author: 'Kitty N Pawell',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Bisexual', 'Erotica', 'Insta-love', 'Sapphic', 'Spicy (High)', 'Strong Female Lead', 'Urban'],
    cover: '/covers/lustDrunkNights.jpg',
    description: "Lust Drunk Nights is a spicy read that will grip you tightly and leave you thirsty for more. Rose Thorne is the ultimate badass, who knows exactly what she wants and isn't afraid to go after it and claim it.",
    link: 'https://a.co/d/hegob75',
  },
  {
    id: 13,
    title: "The Warmest Melody",
    author: 'N. Sonia Nkera',
    ageRange: ['Young Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Enemies to Lovers', 'Incapable of Love', 'Sensitive Content', 'No Spice', 'Sunshine x Grumpy', 'Work Place'],
    cover: '/covers/warmestMelody.jpg',
    description: "Leah is excited to start her hospital residency under the young genius professor, Dante Guma. As the hospital's youngest professor and head of pediatrics, Dante is known for his brilliance and reserve. Even more than that, everyone knows that he prefers to work alone; Leah is the fresh thorn in his side.",
    link: 'https://www.amazon.com/dp/B0CKTMH8YW',
  },
  {
    id: 14,
    title: "Where the River Meets the Soul",
    author: 'S. Nicole',
    ageRange: ['Young Adult'],
    subGenres: ['Family Love', 'Platonic Love', 'Romantic Love'],
    tropes: ['Asexual', 'Bisexual', 'Fantasy', 'Fated Love', 'Forbidden Love', 'Friends to Lovers', 'Queer'],
    cover: '/covers/riverMeetsSoul.png',
    description: " It follows Heriath, an herbalist who goes on a mission to restore a magical flower to save her dying sister. She must reunite reincarnated soulmates to complete her task which proves easy at first, until she finds herself falling for one of the bonded pair.",
    link: 'https://www.amazon.com/dp/B0CGY3NQW6',
  },
  {
    id: 15,
    title: "Stroke Of Luck - Men If Nirvana Book One",
    author: 'Phoenix Collins',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Erotica', 'Forced Proximity', 'Incapable of Love', 'Sensitive Content', 'Spicy (High)', 'Strong Female Lead', 'Work Place'],
    cover: '/covers/strokeOfLuck.jpg',
    description: "When Carter Harrington, a billionaire who avoids emotional attachments, offers to help Lucky, a dancer rebuilding her life after heartbreak, sparks fly. What begins as a friends with benefits arrangement soon grows into something deeper, forcing them to face their fears and vulnerabilities. Together, they must decide if they can trust love enough to create a future neither thought possible.",
    link: 'https://a.co/d/2Oc6Jjo',
  },
  {
    id: 16,
    title: "How Far Is The Nearest Subway?",
    author: 'A M. R. S. K',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love', 'Familial Love', 'Platonic love'],
    tropes: ['Age Gap', 'Coming of Age', 'Contemporary', 'Found Family', 'Friends to Lovers', 'Interracial', 'Strong Female Lead', 'Unplanned Pregnancy', 'Work Place'],
    cover: '/covers/subway.jpeg',
    description: "A fish out of water story, “How Far Is The Nearest Subway?” centers around five friends who are M.R.S. Ks (moms raising southern kids). Through their life experiences as “framily”, these characters navigate living in their adopted hometown, Atlanta, Georgia, with friendship and laughter.",
    link: 'https://a.co/d/bLCE2KJ',
  },
  {
    id: 17,
    title: "Brandy",
    author: 'Kayla Love',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Fake Relationship', 'Small Town', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/brandy.jpg',
    description: "Brandy is looking forward to escaping to Bliss Bay for the summer. Imagine her surprise, when her ex unexpectedly shows up - with his new girlfriend! To pretend she's moved on, Brandy makes up a fake boyfriend. A serendipitous meeting leads to her finding a co conspirator for the ruse. While getting to know him, Brandy catches real feelings. But when complications arise, Brandy must decide: keep up the charade or risk it all for something genuine.",
    link: 'https://a.co/d/1QBosMc',
  },
  {
    id: 18,
    title: "Shoot For The Stars",
    author: 'Ciana Smoak',
    ageRange: ['Young Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Found Family', 'Friends to Lovers', 'Spice Not Included'],
    cover: '/covers/shootForStars.jpeg',
    description: "Journey Young starts fresh at a new School to win a track championship. She meets her childhood friend Roman and tries to focus on herself and not her growing feelings for Roman.",
    link: 'https://a.co/d/iOWpTre',
  },
  {
    id: 19,
    title: "Love Exists Here",
    author: "Rayona Lovely Wilson",
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Forbidden Love', 'Gay', 'Morally Gray', 'Queer', 'Sensitive Content', 'Spice Not Included'],
    cover: '/covers/loveExistsHere.jpeg',
    description: "Kyrie thought he found magic when he met Velvet Noir, a dazzling drag queen full of mystery and allure. But when fate brought him face-to-face with Evan—the shy, wounded man behind the persona—he realized love could be even more transformative than he imagined. As their bond deepens, they must navigate the secrets and darkness threatening to pull them apart, proving that love&apos;s light can heal even the deepest wounds.",
    link: 'https://a.co/d/h422UYq',
  },
  {
    id: 20,
    title: "Entanglement of Love Stories",
    author: 'S. Cassadera',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Damsel in Distress', 'Enemies to Lovers', 'Forced Proximity', 'Insta-love', 'Interracial', 'Mystery', 'Spicy (High)', 'Unplanned Pregnancy', 'Urban', 'Work Place'],
    cover: '/covers/entanglementOfLoveStories.jpeg',
    description: "This is a collection of five contemporary urban short stories that explores themes of friendship, trust, forgiveness, and love overcoming challenges. A collection of  passionate and unpredictable romances.",
    link: 'https://amzn.to/3mXf55d',
  },
  {
    id: 21,
    title: "Love at Second Sight",
    author: 'Ayoka B.',
    ageRange: ['Mature'],
    subGenres: ['Familial Love', 'Platonic Love', 'Romantic Love', 'Self Love'],
    tropes: ['Contemporary', 'Fated Love', 'Found Family', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/loveAtSecondSight.jpeg',
    description: "Shane's life is full... of poetry, motherhood and friends. She is a Single Mom who is pensive, passionate and generous and loves her family. Ambitious and hard-working, Shane is carving her path. Enter Mike. He is talented, complicated and guarded. Their undeniable connection changes their hearts and lives. Love At Second Sight will make you laugh, cry, and cheer and inspire you to rethink what it means to love.",
    link: 'https://www.amazon.com/dp/B0CZ1KTHHM',
  },
  {
    id: 22,
    title: "Love Never",
    author: 'Terrecce M. Clarke',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Fated Love', 'Insta-love', 'Small Town', 'Spicy (High)', 'Strong Female Lead', 'Unplanned Pregnancy'],
    cover: '/covers/loveNever.jpg',
    description: "Elise McDonald kept one eye out for her next adventure and one on the calendar counting down to her new job as an associate professor. Life was meant to be experienced especially when life handed her a biker who was as suave as his name suggested. For one weekend she allowed herself to spend 96 hours in heaven. Damn the consequences.",
    link: 'https://amzn.to/40AeAno',
  },
  {
    id: 23,
    title: "Noora and Bilal Do (each other for) Christmas",
    author: 'Nikki Clarke',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Contemporary', 'Friends to Lovers', 'Spicy (High)'],
    cover: '/covers/nooraAndBilal.jpg',
    description: "It's been a decade since nerdy best friends Noora and Bilal made a high school pact to marry each other. Ten years later, they're both successful and alone at their high school Christmas reunion, and Bilal is ready to fulfill the pact. Noora's life is a little more complicated, but they can agree on one thing—a little fun between two old friends is fine, at least for the holidays.",
    link: 'https://www.amazon.com/dp/B0DPNS3B1G',
  },
  {
    id: 24,
    title: "Please, In your Dreams",
    author: 'Airicia Jones',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love', 'Self Love'],
    tropes: ['Enemies to Lovers', 'Forced Proximity', 'Incapable of Love', 'Rivals to Lovers', 'Spicy (Low)', 'Strong Female Lead', 'Urban'],
    cover: '/covers/pleaseInYourDreams.jpeg',
    description: 'Rochelle "Reese" Reed is focused on becoming "Professor Reed" at Drexel University, leaving no room for love or distractions. When a charming new colleague threatens her career plans and captures her heart, Reese must choose between ambition, ethics, and the possibility of love.',
    link: 'https://www.amazon.com/dp/B0DPFR8V5G',
  },
  {
    id: 25,
    title: "Miles Apart",
    author: 'Tanvier Peart',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Contemporary', 'Enemies to Lovers', 'Fake Relationship', 'Forced Proximity', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/milesApart.jpg',
    description: "Miles Apart is a frenemies-to-lovers story about two people who swear off relationships and get caught up in a thing called love. This spicy book is perfect for romance readers who enjoy tension, banter, and love finding a way.",
    link: 'https://www.amazon.com/dp/B0CYH2XZ21/',
  },
  {
    id: 26,
    title: "Firefly",
    author: 'Tamara Whitlow',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Spicy (High)', 'Work Place'],
    cover: '/covers/firefly.jpg',
    description: "When Jace wants something, he&apos;ll do everything in his power to achieve it. What he wants now is Renee and he&apos;s willing to deceive her into working for him to get her. Will she fall for his tricks, or finally be the one that got away.",
    link: 'https://www.amazon.com/dp/B09H9GZTZB',
  },
  {
    id: 27,
    title: "Head Rush: A Prophecy Series Romantasy Novella",
    author: 'Liz Bullard',
    ageRange: ['Young Adult'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Coming of Age', 'Fantasy', 'Fated Love', 'Strong Female Lead'],
    cover: '/covers/headRush.jpeg',
    description: "Talia, determined to forge her own path, tries to resist Sage Onmai&apos;s meddling in matters of the heart. However, Eli, driven by an unwavering connection, pursues a deeper bond that transcends the physical realm. As their desires intertwine, a question lingers: Will the nefarious Ida, Talia's nemesis, succeed in driving a wedge between them, or will fate prevail, uniting them in both love and war?",
    link: 'https://www.amazon.com/dp/B0CNQ8GSKC/',
  },
  {
    id: 28,
    title: "Sabella Castella: Capturing a Thug's Heart",
    author: 'Deidre Leshay',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Fated Love', 'Urban'],
    cover: '/covers/sabellaCastella.jpeg',
    description: "A man trying to move on with his life after I finding out the kids he loved are not his kids",
    link: 'https://amzn.to/3DZyXBE',
  },
]