import { Book } from '@/app/types';

export const books: Book[] = [
  {
    id: 1,
    title: 'The Gems',
    author: 'M.C. Jeter',
    ageRange: ['New Adult'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Fantasy', 'Contemporary', 'Friends to Lovers', 'Found Family', 'Sensitive Content', 'Strong Female Lead'],
    cover: '/covers/thegems.png',
    description: 'When seventeen-year-old Ruby Jenkins discovers that her blood carries powerful magic, she must band together with new allies to stop her uncle from terrorizing the world.',
    link: 'https://a.co/d/hofcGNV',
  },
  {
    id: 2,
    title: 'Itchikan',
    author: 'Bin Userkaf',
    ageRange: ['Young Adult'],
    subGenres: ['Platonic Love', 'Self Love', 'Romantic Love'],
    tropes: ['Comedy', 'Coming of Age', 'Contemporary', 'Dystopian', 'Fantasy', 'Found Family', 'Friends to Lovers', 'Sci-Fi', 'Strong Female Lead'],
    cover: '/covers/itchikan.jpg',
    description: 'Seventeen year old Aurora’s sheltered life is changed forever when the merciless Queen of her hometown, Navajo City-State, announces a nefarious experiment that threatens the few things she holds dear.  Tired of sitting on the sidelines and eager for adventure, Aurora and her friends set out to stop it, sending them on a journey of chaotic proportions when things don’t go as planned and they are forced to flee to Itchikan City-State.   Friendships are tested and foes are formed, but war is no place for the kind of adventure Aurora had in mind and if they are going to defeat the Queen, she will first have to defeat the darkness within herself.',
    link: 'https://a.co/d/cwu3sDM',
  },
  {
    id: 3,
    title: 'Lipstick & Camera Clicks',
    author: 'D. J. Murphy',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love', 'Familial Love'],
    tropes: ['Contemporary', 'Forced Proximity', 'Friends to Lovers', 'Interracial', 'Spicy (Low)', 'Strong Female Lead'],
    cover: '/covers/lipstickAndCam.jpg',
    description: 'Indigo Johnson joins the cast of a reality dating show after a recent heartbreak leaves her craving change. She never expected to develop real feelings for the bachelor—or that her childhood best friend, now the show’s producer, would reignite emotions she thought were long buried. Now, she’s caught in the spotlight, struggling to resist the growing spark with the leading man while pretending she’s over the one working behind the scenes.',
    link: 'https://a.co/d/1oEl7XA',
  },
  {
    id: 4,
    title: 'Bali Blue: A Wanderlust Romance Novel',
    author: 'Cher Terais',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love', 'Self Love'],
    tropes: ['Contemporary', 'Enemies to Lovers', 'Forced Proximity', 'Spicy (High)', 'Strong Female Lead', 'Work Place'],
    cover: '/covers/baliBlue.jpg',
    description: 'After Rhiyan’s marriage crashed and burned, she packed up and flew to Bali. Instead of healing, she’s met with a headache—Kendrick Kekoa. The tropical heat has nothing on the sparks between these two in Bali!',
    link: 'https://a.co/d/63DyzYE',
  },// Add more book objects...
  {
    id: 5,
    title: 'Recovery (A Marriage in Crisis)',
    author: 'Tay Latrese',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary', 'Forced Proximity', 'Spicy (Low)', 'Urban'],
    cover: '/covers/recovery.jpeg',
    description: 'Maurice and Neyehli Logan have been together for over a decade and have hit a roadblock in their marriage; tragedy. The two agree to book a weekend trip out in the middle of nowhere to try and salvage their relationship.',
    link: 'https://a.co/d/2bi9CnS',
  },
  {
    id: 6,
    title: 'Spend My Life With You',
    author: 'Monique Fisher',
    ageRange: ['Mature'],
    subGenres: ['Familial Love', 'Romantic Love'],
    tropes: ['Comedy', 'Contemporary', 'Friends to Lovers', 'Spicy (High)', 'Strong Female Lead'],
    cover: '/covers/spendMyLifeWithYou.jpg',
    description: 'Thaddeus Richardson and Andrea Johnson are in love. Having wasted years staying quiet, they confess their feelings and immediately get married. The book follows their first year of marriage.',
    link: 'https://www.amazon.com/dp/B0DJWQBLLW',
  },
  {
    id: 7,
    title: 'Breaking Point: Chandler’s Choice',
    author: 'Carlotta Ardell',
    ageRange: ['Young Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Contemporary'],
    cover: '/covers/breakingPoint.jpg',
    description: 'Chandler Gray never imagined during her journey to earn a nursing degree, she would encounter a distraction, in the form of firefighter, Moses Lawson. With the chaos of supporting her mother after her father’s passing and completing her internship and practicum, Chandler had no time for a relationship. However, Moses’ persistence, charisma, and rugged good looks made her think again. Perhaps a summer fling with no strings attached was just what the doctor ordered.  Unfortunately, their situationship became much more than she bargained for. Now Chandler wants Moses to switch things up to be in a committed and monogamous relationship. His response causes Chandler to react in ways she may come to regret.  Years later, when their paths cross in very different circumstances, Chandler will have another decision to make.  Can she look beyond her own hurt to give of herself and heal another past their breaking point?',
    link: 'https://a.co/d/d5Aqgcj',
  },
  {
    id: 8,
    title: 'Project Protection',
    author: 'Aiyana McCoy',
    ageRange: ['New Adult'],
    subGenres: ['Romantic Love'],
    tropes: ['Fake Relationship', 'Forced Proximity', 'Interracial', 'Strong Female Lead', 'Sunshine x Grumpy'],
    cover: '/covers/projectProtection.jpg',
    description: 'Amelie a gun for hire becomes a bodyguard for the son of a CEO who is in danger from a mysterious attacker. He also asks her to be his fake girlfriend to keep his mother from trying to marry him off. ',
    link: 'https://www.amazon.com/dp/B0CL2D3FJC',
  },
  {
    id: 9,
    title: "She’s A Grinder",
    author: 'Tember Sapphire',
    ageRange: ['Mature'],
    subGenres: ['Romantic Love'],
    tropes: ['Comedic', 'Contemporary', 'Fake Relationship', 'Forbidden Love', 'Forced Proximity', 'Found Family', 'Strong Female Lead', 'Sunshine x Grumpy', 'Work Place'],
    cover: '/covers/shesAGrinder.jpg',
    description: 'She’s A Grinder is a fake dating hockey romance featuring Catherine a sports executive and her best friend’s brother and hockey grinder Tijjani.',
    link: 'https://a.co/d/0fNoXrU',
  },
  {
    id: 10,
    title: "Title",
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: "Description of Book Here",
    link: 'https://www.example.com',
  },
  {
    id: 11,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 12,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 13,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 14,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
  {
    id: 3,
    title: 'Title',
    author: 'Author',
    ageRange: ['Age Range'],
    subGenres: ['Type of Love', 'Type of Love'],
    tropes: ['Trope Here', 'Trope Here', 'Trope Here'],
    cover: '/covers/comingSoon1.jpg',
    description: 'Description of Book Here',
    link: 'https://www.example.com',
  },
